version: '3.7'

services:
  postgres:
    container_name: inventory_service
    image: postgres:17.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_service
    ports:
      - "5434:5432"
    volumes:
      - /c/Users/surya/Documents/workspace/inventory-service/docker/postgres:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql